incremental improvements

diff --git a/hax/test/configure b/hax/test/configure
--- a/hax/test/configure
+++ b/hax/test/configure
@@ -13,11 +13,20 @@ setconf()
 
   c_src "src/avltree.c"
   c_src "src/printf.c"
+
+  c_src "src/sys/thread.c"
 }
 ## end configuration options ##
 
+## begin custom options ##
+opt()
+{
+  return 0
+}
+## end custom options ##
 
-##### marc_andrysco configure script, rev 2 #####
+
+##### marc_andrysco configure script, rev 5 #####
 
 # special characters
 nl="`printf '\nX'`" ; nl="${nl%X}"
@@ -43,6 +52,7 @@ bin_target()
   chk_space "$1" || fail "bin_target parameter '$1' has spaces"
 
   target="$1"
+  install="${install}${nl}${tab}install --mode 0755 -D $1 \$(BINDIR)/$1"
 }
 
 # Set the library target
@@ -54,8 +64,8 @@ lib_target()
   test ${1##*.} != "so" && fail "lib_target argument has invalid extension '.${1##*.}'"
   ldflags="$ldflags -shared"
 
-  target="$1"
-  install="${install}${nl}${tab}install --mode 0644 -D $1 \$(LIBDIR)/$1"
+  test "$windows$cygwin" && target=${1%.so}.dll || target=$1
+  install="${install}${nl}${tab}install --mode 0644 -D $target \$(LIBDIR)/$target"
 }
 
 # Set the header target
@@ -69,6 +79,19 @@ hdr_target()
   install="${install}${nl}${tab}install --mode 0644 -D $1 \$(INCDIR)/$1"
 }
 
+# Set the include target
+#   @path: The target path.
+inc_target()
+{
+  test $# -ne 1 && fail "inc_target function takes 1 argument"
+  chk_space "$1" || fail "inc_target parameter '$1' has spaces"
+
+  inc="$1"
+  install="${install}${nl}${tab}install --mode 0644 -D $1 \$(INCDIR)/$1"
+
+  :>"$inc"
+}
+
 # Add a C source file to the Makefile.
 #   @path: The source path.
 c_src()
@@ -79,7 +102,8 @@ c_src()
 
   obj="$obj ${1%.*}.o"
   deps="$deps ${1%.*}.d"
-  test -z "$noinc" && inc="$inc ${1%.*}.h"
+  test -z "$noinc" && hdrs="$hdrs ${1%.*}.h"
+  test "$inc" && inc_src "${1%.*}.h"
 }
 
 # Add a header source file to the Makefile.
@@ -90,7 +114,25 @@ h_src()
   chk_space "$1" || fail "h_src parameter '$1' has spaces"
   test ${1##*.} != "h" && fail "h_src argument has invalid extension '.${1##*.}'"
 
-  inc="$inc $1"
+  hdrs="$hdrs $1"
+  test "$inc" && inc_src "$1"
+}
+
+# Add a header include file.
+#   @path: The source path.
+inc_src()
+{
+  test $# -ne 1 && fail "inc_src function takes 1 argument"
+  chk_space "$1" || fail "inc_src parameter '$1' has spaces"
+  test ${1##*.} != "h" && fail "inc_src argument has invalid extension '.${1##*.}'"
+
+  path="$1"
+  rem="$inc"
+  while [ "$path$rem" ] && [ "${path%%/*}" = "${rem%%/*}" ] ; do
+    path=${path#*/} ; rem=${rem#*/}
+  done
+
+  printf "#include \"%s\"\n" "$path" >> "$inc"
 }
 
 # Add an asset to the share directory.
@@ -166,7 +208,7 @@ for opt in "$@" ; do
 done
 
 # append config.args file
-test -f config.args && eval set -- "`cat config.args | tr '\n\t' '  '`"
+test -f config.args && eval set -- "${args}`cat config.args | tr '\n\t' '  '`"
 
 #initialize options
 toolchain="" #toolchain
@@ -175,20 +217,22 @@ debug=""     #debug flag
 rpath=""     #rpath build
 obj=""       #object files
 windows=""   #windows build
+cygwin=""   #cygwin build
 noinc=""     #disable automated include
+pkgcfg=""    #pkgconfig dependencies
 
 prefix='/usr/local'
 bindir='$(PREFIX)/bin'
 libdir='$(PREFIX)/lib'
 incdir='$(PREFIX)/include'
 sharedir='$(PREFIX)/share'
-cflags='-g -fpic -std=gnu11 -Wall -I$(INCDIR) -MD'
+cflags='-g -O2 -fpic -std=gnu11 -Wall -I$(INCDIR) -MD'
 ldflags='-L$(LIBDIR)'
 
 # parse options
 while [ "$#" -gt 0 ] ; do
   case "$1" in 
-    --release | --debug | --rpath | --windows)
+    --release | --debug | --rpath | --windows | --cygwin)
       eval "${1#--}=1" ; shift
       ;;
     --toolchain=* | --prefix=*)
@@ -196,10 +240,17 @@ while [ "$#" -gt 0 ] ; do
       eval "$name=`quote "$val"`"
       ;;
     *)
-      printf "unknown option '%s'\n" "$1" >&2 ; exit 1
+      opt "$@" && { printf "unknown option '%s'\n" "$1" >&2 ; exit 1 ; }
+      shift $?
       ;;
   esac
 done
+
+# pkgconfig args
+if [ "$pkgcfg" ] ; then
+      cflags="${cflags} \`pkg-config --cflags ${pkgcfg% }\`"
+      ldflags="${ldflags} \`pkg-config --libs ${pkgcfg% }\`"
+fi
 
 # sanity check
 test "$release" && test "$debug" && fail "cannot use both --debug and --release"
@@ -214,7 +265,7 @@ cc="${toolchain}gcc"
 ld="${toolchain}gcc"
 
 # process configuration information
-target="" ; obj="" ; hdr="" ; inc="" ; deps="" ; install=""
+target="" ; obj="" ; hdr="" ; hdrs="" ; inc="" ; deps="" ; install=""
 setconf
 
 test -z "$target" && fail "missing target"
@@ -258,10 +309,10 @@ EOF
 if [ "$hdr" ] ; then
   guard="`printf 'LIB%s_H' "${hdr%%.*}" | tr '[a-z]' '[A-Z]'`"
   cat <<EOF >> "$mkfile"
-$hdr:$inc Makefile
+$hdr:$hdrs Makefile
 	rm -f \$@
 	printf '#ifndef $guard\n#define $guard\n' >> \$@
-	for inc in $inc ; do sed -e'1,2d' -e'\$\$d' \$\$inc >> \$@ ; done
+	for inc in $hdrs ; do sed -e'1,2d' -e'\$\$d' \$\$inc >> \$@ ; done
 	printf '#endif\n' >> \$@
 EOF
 fi
@@ -283,6 +334,7 @@ echo "#ifndef CONFIG_H" >> "$cfg"
 echo "#define CONFIG_H" >> "$cfg"
 test "$debug" && echo "#define DEBUG 1" >> "$cfg"
 test "$windows" && echo "#define WINDOWS 1" >> "$cfg"
+test "$cygwin" && echo "#define CYGWIN 1" >> "$cfg"
 echo "#define SHAREDIR \"${prefix}/share"\" >> "$cfg"
 echo "#endif" >> "$cfg"
 
