one week commit

diff --git a/hax/configure b/hax/configure
--- a/hax/configure
+++ b/hax/configure
@@ -5,6 +5,7 @@ setconf()
 {
   lib_target "libhax.so"
   hdr_target "hax.h"
+  inc_target "src/inc.h"
 
   h_src "src/defs.h"
 
@@ -17,10 +18,12 @@ setconf()
   fi
 
   if [ "$windows" ] ; then
+    h_src "src/win/defs.h"
     c_src "src/win/poll.c"
     c_src "src/win/sock.c"
     c_src "src/win/thread.c"
   else
+    h_src "src/posix/defs.h"
     c_src "src/posix/poll.c"
     c_src "src/posix/sock.c"
     c_src "src/posix/thread.c"
@@ -35,6 +38,7 @@ setconf()
   c_src "src/list.c"
   c_src "src/mem.c"
   c_src "src/print.c"
+  c_src "src/rand.c"
   c_src "src/strbuf.c"
 
   c_src "src/http.c"
@@ -50,7 +54,7 @@ opt()
 ## end custom options ##
 
 
-##### marc_andrysco configure script, rev 3 #####
+##### marc_andrysco configure script, rev 4 #####
 
 # special characters
 nl="`printf '\nX'`" ; nl="${nl%X}"
@@ -103,6 +107,19 @@ hdr_target()
   install="${install}${nl}${tab}install --mode 0644 -D $1 \$(INCDIR)/$1"
 }
 
+# Set the include target
+#   @path: The target path.
+inc_target()
+{
+  test $# -ne 1 && fail "inc_target function takes 1 argument"
+  chk_space "$1" || fail "inc_target parameter '$1' has spaces"
+
+  inc="$1"
+  install="${install}${nl}${tab}install --mode 0644 -D $1 \$(INCDIR)/$1"
+
+  :>"$inc"
+}
+
 # Add a C source file to the Makefile.
 #   @path: The source path.
 c_src()
@@ -113,7 +130,8 @@ c_src()
 
   obj="$obj ${1%.*}.o"
   deps="$deps ${1%.*}.d"
-  test -z "$noinc" && inc="$inc ${1%.*}.h"
+  test -z "$noinc" && hdrs="$hdrs ${1%.*}.h"
+  test "$inc" && inc_src "${1%.*}.h"
 }
 
 # Add a header source file to the Makefile.
@@ -124,7 +142,25 @@ h_src()
   chk_space "$1" || fail "h_src parameter '$1' has spaces"
   test ${1##*.} != "h" && fail "h_src argument has invalid extension '.${1##*.}'"
 
-  inc="$inc $1"
+  hdrs="$hdrs $1"
+  test "$inc" && inc_src "$1"
+}
+
+# Add a header include file.
+#   @path: The source path.
+inc_src()
+{
+  test $# -ne 1 && fail "inc_src function takes 1 argument"
+  chk_space "$1" || fail "inc_src parameter '$1' has spaces"
+  test ${1##*.} != "h" && fail "inc_src argument has invalid extension '.${1##*.}'"
+
+  path="$1"
+  rem="$inc"
+  while [ "$path$rem" ] && [ "${path%%/*}" = "${rem%%/*}" ] ; do
+    path=${path#*/} ; rem=${rem#*/}
+  done
+
+  printf "#include \"%s\"\n" "$path" >> "$inc"
 }
 
 # Add an asset to the share directory.
@@ -256,7 +292,7 @@ cc="${toolchain}gcc"
 ld="${toolchain}gcc"
 
 # process configuration information
-target="" ; obj="" ; hdr="" ; inc="" ; deps="" ; install=""
+target="" ; obj="" ; hdr="" ; hdrs="" ; inc="" ; deps="" ; install=""
 setconf
 
 test -z "$target" && fail "missing target"
@@ -300,10 +336,10 @@ EOF
 if [ "$hdr" ] ; then
   guard="`printf 'LIB%s_H' "${hdr%%.*}" | tr '[a-z]' '[A-Z]'`"
   cat <<EOF >> "$mkfile"
-$hdr:$inc Makefile
+$hdr:$hdrs Makefile
 	rm -f \$@
 	printf '#ifndef $guard\n#define $guard\n' >> \$@
-	for inc in $inc ; do sed -e'1,2d' -e'\$\$d' \$\$inc >> \$@ ; done
+	for inc in $hdrs ; do sed -e'1,2d' -e'\$\$d' \$\$inc >> \$@ ; done
 	printf '#endif\n' >> \$@
 EOF
 fi
