i dont even know anymore

diff --git a/core/configure b/core/configure
--- a/core/configure
+++ b/core/configure
@@ -5,12 +5,15 @@ setconf()
 {
   lib_target "libampcore.so"
   hdr_target "amplib.h"
+  inc_target "src/inc.h"
 
-  lib_dep "hax"
-  lib_dep "dsp"
   lib_dep "muselang"
+  lib_dep "dsp"
+  lib_dep "hax"
 
+  h_src "src/debug.h"
   h_src "src/defs.h"
+
   h_src "src/clk/defs.h"
   h_src "src/efx/defs.h"
   h_src "src/instr/defs.h"
@@ -48,6 +51,7 @@ setconf()
   c_src "src/efx/sect.c"
   c_src "src/efx/shaper.c"
   c_src "src/efx/track.c"
+  c_src "src/efx/wrap.c"
   c_src "src/efx/vol.c"
 
   c_src "src/eval/sched.c"
@@ -87,7 +91,7 @@ opt()
 ## end custom options ##
 
 
-##### marc_andrysco configure script, rev 3 #####
+##### marc_andrysco configure script, rev 4 #####
 
 # special characters
 nl="`printf '\nX'`" ; nl="${nl%X}"
@@ -113,6 +117,7 @@ bin_target()
   chk_space "$1" || fail "bin_target parameter '$1' has spaces"
 
   target="$1"
+  install="${install}${nl}${tab}install --mode 0755 -D $1 \$(BINDIR)/$1"
 }
 
 # Set the library target
@@ -125,7 +130,7 @@ lib_target()
   ldflags="$ldflags -shared"
 
   target="$1"
-  install="${install}${nl}${tab}install --mode 0755 -D $1 \$(LIBDIR)/$1"
+  install="${install}${nl}${tab}install --mode 0644 -D $1 \$(LIBDIR)/$1"
 }
 
 # Set the header target
@@ -139,6 +144,19 @@ hdr_target()
   install="${install}${nl}${tab}install --mode 0644 -D $1 \$(INCDIR)/$1"
 }
 
+# Set the include target
+#   @path: The target path.
+inc_target()
+{
+  test $# -ne 1 && fail "inc_target function takes 1 argument"
+  chk_space "$1" || fail "inc_target parameter '$1' has spaces"
+
+  inc="$1"
+  install="${install}${nl}${tab}install --mode 0644 -D $1 \$(INCDIR)/$1"
+
+  :>"$inc"
+}
+
 # Add a C source file to the Makefile.
 #   @path: The source path.
 c_src()
@@ -149,7 +167,8 @@ c_src()
 
   obj="$obj ${1%.*}.o"
   deps="$deps ${1%.*}.d"
-  test -z "$noinc" && inc="$inc ${1%.*}.h"
+  test -z "$noinc" && hdrs="$hdrs ${1%.*}.h"
+  test "$inc" && inc_src "${1%.*}.h"
 }
 
 # Add a header source file to the Makefile.
@@ -160,7 +179,25 @@ h_src()
   chk_space "$1" || fail "h_src parameter '$1' has spaces"
   test ${1##*.} != "h" && fail "h_src argument has invalid extension '.${1##*.}'"
 
-  inc="$inc $1"
+  hdrs="$hdrs $1"
+  test "$inc" && inc_src "$1"
+}
+
+# Add a header include file.
+#   @path: The source path.
+inc_src()
+{
+  test $# -ne 1 && fail "inc_src function takes 1 argument"
+  chk_space "$1" || fail "inc_src parameter '$1' has spaces"
+  test ${1##*.} != "h" && fail "inc_src argument has invalid extension '.${1##*.}'"
+
+  path="$1"
+  rem="$inc"
+  while [ "$path$rem" ] && [ "${path%%/*}" = "${rem%%/*}" ] ; do
+    path=${path#*/} ; rem=${rem#*/}
+  done
+
+  printf "#include \"%s\"\n" "$path" >> "$inc"
 }
 
 # Add an asset to the share directory.
@@ -292,7 +329,7 @@ cc="${toolchain}gcc"
 ld="${toolchain}gcc"
 
 # process configuration information
-target="" ; obj="" ; hdr="" ; inc="" ; deps="" ; install=""
+target="" ; obj="" ; hdr="" ; hdrs="" ; inc="" ; deps="" ; install=""
 setconf
 
 test -z "$target" && fail "missing target"
@@ -336,10 +373,10 @@ EOF
 if [ "$hdr" ] ; then
   guard="`printf 'LIB%s_H' "${hdr%%.*}" | tr '[a-z]' '[A-Z]'`"
   cat <<EOF >> "$mkfile"
-$hdr:$inc Makefile
+$hdr:$hdrs Makefile
 	rm -f \$@
 	printf '#ifndef $guard\n#define $guard\n' >> \$@
-	for inc in $inc ; do sed -e'1,2d' -e'\$\$d' \$\$inc >> \$@ ; done
+	for inc in $hdrs ; do sed -e'1,2d' -e'\$\$d' \$\$inc >> \$@ ; done
 	printf '#endif\n' >> \$@
 EOF
 fi
