one big commit

diff --git a/core/configure b/core/configure
--- a/core/configure
+++ b/core/configure
@@ -1,5 +1,189 @@
 #!/bin/sh
 
+## begin configuration options ##
+setconf()
+{
+  lib_target "libampcore.so"
+  hdr_target "amplib.h"
+
+  lib_dep "hax"
+  lib_dep "dsp"
+  lib_dep "muselang"
+
+  h_src "src/defs.h"
+  h_src "src/clk/defs.h"
+  h_src "src/efx/defs.h"
+  h_src "src/instr/defs.h"
+  h_src "src/mod/defs.h"
+  h_src "src/seq/defs.h"
+
+  c_src "src/box.c"
+  c_src "src/cache.c"
+  c_src "src/core.c"
+  c_src "src/ctrl.c"
+  c_src "src/key.c"
+  c_src "src/io.c"
+  c_src "src/math.c"
+  c_src "src/param.c"
+
+  c_src "src/clk/basic.c"
+
+  c_src "src/efx/bias.c"
+  c_src "src/efx/bitcrush.c"
+  c_src "src/efx/chain.c"
+  c_src "src/efx/chorus.c"
+  c_src "src/efx/clip.c"
+  c_src "src/efx/comp.c"
+  c_src "src/efx/effect.c"
+  c_src "src/efx/expcrush.c"
+  c_src "src/efx/filt.c"
+  c_src "src/efx/gain.c"
+  c_src "src/efx/gate.c"
+  c_src "src/efx/gen.c"
+  c_src "src/efx/loop.c"
+  c_src "src/efx/mix.c"
+  c_src "src/efx/octave.c"
+  c_src "src/efx/reverb.c"
+  c_src "src/efx/scale.c"
+  c_src "src/efx/sect.c"
+  c_src "src/efx/track.c"
+  c_src "src/efx/vol.c"
+
+  c_src "src/eval/sched.c"
+
+  c_src "src/instr/inject.c"
+  c_src "src/instr/mixer.c"
+  c_src "src/instr/series.c"
+  c_src "src/instr/single.c"
+  c_src "src/instr/splice.c"
+
+  c_src "src/mod/adsr.c"
+  c_src "src/mod/mul.c"
+  c_src "src/mod/noise.c"
+  c_src "src/mod/osc.c"
+  c_src "src/mod/patch.c"
+  c_src "src/mod/sample.c"
+  c_src "src/mod/shot.c"
+  c_src "src/mod/sum.c"
+  c_src "src/mod/synth.c"
+  c_src "src/mod/trig.c"
+
+  c_src "src/seq/merge.c"
+  c_src "src/seq/player.c"
+  c_src "src/seq/repeat.c"
+  c_src "src/seq/sched.c"
+  c_src "src/seq/snap.c"
+  c_src "src/seq/toggle.c"
+}
+## end configuration options ##
+
+## begin custom options ##
+opt()
+{
+  return 0
+}
+## end custom options ##
+
+
+##### marc_andrysco configure script, rev 3 #####
+
+# special characters
+nl="`printf '\nX'`" ; nl="${nl%X}"
+tab="`printf '\tX'`" ; tab="${tab%X}"
+
+# Check if a string has a space
+#   @str: The string.
+#   &returns: Non-zero if space found, zero otherwise.
+chk_space()
+{
+  for __chk_space in "$@" ; do
+    test -z "${__chk_space%%* *}" && return 1
+    test -z "${__chk_space%%*	*}" && return 1
+  done
+  return 0
+}
+
+# Set the binary target
+#   @path: The target path.
+bin_target()
+{
+  test $# -ne 1 && fail "bin_target function takes 1 argument"
+  chk_space "$1" || fail "bin_target parameter '$1' has spaces"
+
+  target="$1"
+}
+
+# Set the library target
+#   @path: The target path.
+lib_target()
+{
+  test $# -ne 1 && fail "lib_target function takes 1 argument"
+  chk_space "$1" || fail "lib_target parameter '$1' has spaces"
+  test ${1##*.} != "so" && fail "lib_target argument has invalid extension '.${1##*.}'"
+  ldflags="$ldflags -shared"
+
+  target="$1"
+  install="${install}${nl}${tab}install --mode 0755 -D $1 \$(LIBDIR)/$1"
+}
+
+# Set the header target
+#   @path: The target path.
+hdr_target()
+{
+  test $# -ne 1 && fail "hdr_target function takes 1 argument"
+  chk_space "$1" || fail "hdr_target parameter '$1' has spaces"
+
+  hdr="$1"
+  install="${install}${nl}${tab}install --mode 0644 -D $1 \$(INCDIR)/$1"
+}
+
+# Add a C source file to the Makefile.
+#   @path: The source path.
+c_src()
+{
+  test $# -ne 1 && fail "c_src function takes 1 argument"
+  chk_space "$1" || fail "c_src parameter '$1' has spaces"
+  test ${1##*.} != "c" && fail "c_src argument has invalid extension '.${1##*.}'"
+
+  obj="$obj ${1%.*}.o"
+  deps="$deps ${1%.*}.d"
+  test -z "$noinc" && inc="$inc ${1%.*}.h"
+}
+
+# Add a header source file to the Makefile.
+#   @path: The source path.
+h_src()
+{
+  test $# -ne 1 && fail "h_src function takes 1 argument"
+  chk_space "$1" || fail "h_src parameter '$1' has spaces"
+  test ${1##*.} != "h" && fail "h_src argument has invalid extension '.${1##*.}'"
+
+  inc="$inc $1"
+}
+
+# Add an asset to the share directory.
+#   @path: The source path.
+share_src()
+{
+  test $# -ne 2 && fail "share_src function takes 2 arguments"
+  chk_space "$1" || fail "share_src parameter '$1' has spaces"
+  chk_space "$2" || fail "share_src parameter '$2' has spaces"
+
+  install="${install}${nl}${tab}install --mode 0644 -D $1 \$(SHAREDIR)/$2"
+}
+
+
+# Add a library as dependency
+#   @lib: The library name without prefix 'lib' or postfix '.so'.
+lib_dep()
+{
+  test $# -ne 1 && fail "lib_dep function takes 1 argument"
+  chk_space "$1" || fail "lib_dep parameter '$1' has spaces"
+
+  ldflags="$ldflags -l$1"
+}
+
+
 ##
 # quote Function
 #   Given the input string, it places it within single quotes, making sure that
@@ -27,6 +211,22 @@ quote()
 	printf %s "'$__quote_str'"
 }
 
+##
+# fail Function
+#   Print an error message and terminate. The function does not return.
+# Version
+#   1.0
+# Parameters
+#   string err
+#     The error string.
+#.
+fail()
+{
+  printf 'error: %s\n' "$*" >&2
+  exit 1
+}
+
+
 # build arguments list
 args=""
 for opt in "$@" ; do
@@ -34,52 +234,132 @@ for opt in "$@" ; do
 done
 
 # append config.args file
-test -f config.args && eval set -- "`cat config.args | tr '\n\t' '  '`"
+test -f config.args && eval set -- "${args}`cat config.args | tr '\n\t' '  '`"
 
-# parse options
-rpath=0
+#initialize options
+toolchain="" #toolchain
+release=""   #release flag
+debug=""     #debug flag
+rpath=""     #rpath build
+obj=""       #object files
+windows=""   #windows build
+noinc=""     #disable automated include
+pkgcfg=""    #pkgconfig dependencies
+
 prefix='/usr/local'
 bindir='$(PREFIX)/bin'
 libdir='$(PREFIX)/lib'
 incdir='$(PREFIX)/include'
 sharedir='$(PREFIX)/share'
-cflags='-O2 -g -fpic `pkg-config --cflags sndfile` -ffast-math -Wall -I$(INCDIR) '
-ldflags='-lm -ldsp -lmuselang -lhax `pkg-config --libs sndfile` -ffast-math -L$(LIBDIR) '
+cflags='-g -fpic -std=gnu11 -Wall -I$(INCDIR) -MD'
+ldflags='-L$(LIBDIR)'
+
+# parse options
 while [ "$#" -gt 0 ] ; do
   case "$1" in 
-    --rpath)
-      rpath=1 ; shift
+    --release | --debug | --rpath | --windows)
+      eval "${1#--}=1" ; shift
       ;;
-    --prefix)
-      test "$#" -eq 1 && { printf "missing prefix parameter" >&2 ; exit 1 ; }
-      prefix="$2" ; shift 2
-      ;;
-    --prefix=*)
-      prefix="${1#*=}" ; shift
-      ;;
-    --debug)
-      cflags="$cflags-Werror -DDEBUG " ; shift
+    --toolchain=* | --prefix=*)
+      name="${1#--}" ; name="${name%%=*}" ; val="${1#*=}" ; shift
+      eval "$name=`quote "$val"`"
       ;;
     *)
-      printf "unknown option '%s'\n" "$1" >&2 ; exit 1
+      opt "$@" && { printf "unknown option '%s'\n" "$1" >&2 ; exit 1 ; }
+      shift $?
       ;;
   esac
 done
 
+# pkgconfig args
+if [ "$pkgcfg" ] ; then
+      cflags="${cflags} \`pkg-config --cflags ${pkgcfg% }\`"
+      ldflags="${ldflags} \`pkg-config --libs ${pkgcfg% }\`"
+fi
+
+# sanity check
+test "$release" && test "$debug" && fail "cannot use both --debug and --release"
+
+# delayed options
 test "$rpath" && ldflags="$ldflags -Wl,-rpath=\$(LIBDIR)"
+test "$debug" && cflags="$cflags -Werror"
+
+# build tools
+test "$toolchain" && toolchain="$toolchain-"
+cc="${toolchain}gcc"
+ld="${toolchain}gcc"
+
+# process configuration information
+target="" ; obj="" ; hdr="" ; inc="" ; deps="" ; install=""
+setconf
+
+test -z "$target" && fail "missing target"
+test -z "$obj" && fail "missing object files"
 
 # build makefile
-rm -f Makefile
-echo "ARGS     = $args" >> Makefile
-echo "PREFIX   = $prefix" >> Makefile
-echo "BINDIR   = $bindir" >> Makefile
-echo "LIBDIR   = $libdir" >> Makefile
-echo "INCDIR   = $incdir" >> Makefile
-echo "SHAREDIR = $sharedir" >> Makefile
-echo "CFLAGS   = $cflags" >> Makefile
-echo "LDFLAGS  = $ldflags" >> Makefile
-cat Makefile.in >> Makefile
+mkfile="Makefile"
+rm -f "$mkfile"
+cat <<EOF >> "$mkfile"
+CC       = $cc
+LD       = $ld
+
+CFLAGS   = $cflags
+LDFLAGS  = $ldflags
+
+ARGS     = ${args}
+PREFIX   = ${prefix}
+BINDIR   = ${bindir}
+LIBDIR   = ${libdir}
+INCDIR   = ${incdir}
+SHAREDIR = ${sharedir}
+
+all: $target $hdr
+
+$target:$obj
+	\$(CC)  $^ -o \$@ \$(CFLAGS) \$(LDFLAGS)
+
+%.o: %.c Makefile configure
+	\$(CC) -c $< -o \$@ \$(CFLAGS)
+
+Makefile: configure \$(wildcard config.args)
+	./configure \$(ARGS)
+
+clean:
+	rm -f $target $obj
+
+install: all$install
+
+EOF
+
+if [ "$hdr" ] ; then
+  guard="`printf 'LIB%s_H' "${hdr%%.*}" | tr '[a-z]' '[A-Z]'`"
+  cat <<EOF >> "$mkfile"
+$hdr:$inc Makefile
+	rm -f \$@
+	printf '#ifndef $guard\n#define $guard\n' >> \$@
+	for inc in $inc ; do sed -e'1,2d' -e'\$\$d' \$\$inc >> \$@ ; done
+	printf '#endif\n' >> \$@
+EOF
+fi
+
+echo "" >> "$mkfile"
+echo "-include Makefile.user Makefile.proj" >> "$mkfile"
+echo "" >> "$mkfile"
+
+for dep in $deps ; do
+  echo "-include $dep" >> "$mkfile"
+  rm -f "$dep"
+done
 
 # build config.h
-rm -f src/config.h
-echo "#define SHAREDIR \"$prefix/share/amp\"" >> src/config.h
+cfg="src/config.h"
+rm -f "$cfg"
+
+echo "#ifndef CONFIG_H" >> "$cfg"
+echo "#define CONFIG_H" >> "$cfg"
+test "$debug" && echo "#define DEBUG 1" >> "$cfg"
+test "$windows" && echo "#define WINDOWS 1" >> "$cfg"
+echo "#define SHAREDIR \"${prefix}/share"\" >> "$cfg"
+echo "#endif" >> "$cfg"
+
+exit 0
